// <auto-generated />
using DisasterAlarm.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisasterAlarm.context.Migrations
{
    [DbContext(typeof(DisasterAlarmContext))]
    [Migration("20260415121917_UpdateDataTable150426T3")]
    partial class UpdateDataTable150426T3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DisasterAlarm.context.Entities.DisasterType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Disaster")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Disaster")
                        .IsUnique();

                    b.ToTable("DisasterTypes");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegionId")
                        .IsUnique();

                    b.HasIndex(new[] { "Latitude", "Longitude" }, "idx_lat_lon")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.RegionDisaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DisasterTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<float?>("Threshold")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DisasterTypeId");

                    b.HasIndex(new[] { "RegionId", "DisasterTypeId" }, "idx_re_dis")
                        .IsUnique();

                    b.ToTable("RegionDisasters");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.RiskReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AlertTrigger")
                        .HasColumnType("boolean");

                    b.Property<long>("RegionDisasterId")
                        .HasColumnType("bigint");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("RiskScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RegionDisasterId");

                    b.ToTable("RiskReports");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.UserSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "RegionId", "UserId" }, "idx_user_sub")
                        .IsUnique();

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.RegionDisaster", b =>
                {
                    b.HasOne("DisasterAlarm.context.Entities.DisasterType", "DisasterType")
                        .WithMany()
                        .HasForeignKey("DisasterTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisasterAlarm.context.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisasterType");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.RiskReport", b =>
                {
                    b.HasOne("DisasterAlarm.context.Entities.RegionDisaster", "RegionDisaster")
                        .WithMany()
                        .HasForeignKey("RegionDisasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionDisaster");
                });

            modelBuilder.Entity("DisasterAlarm.context.Entities.UserSubscription", b =>
                {
                    b.HasOne("DisasterAlarm.context.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisasterAlarm.context.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
